language: php

php:
  - 7.2
  - 7.3

before_script:
  - cd laravel
  - cp .env.example .env
  - composer install
  - php artisan key:generate

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse