version: '3.7'
services:
  nginx:
    image: nginx:1.17.2-alpine
    ports:
      - '8080:80'
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  php:
    build: ./php
    user: '1000:1000'
    volumes:
      - ./laravel:/var/www/html
      - ./php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./php/php.ini-production:/usr/local/etc/php/php.ini-production
      - ./php/docker-php-ext-sodium.ini:/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: laravel
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  composer:
    image: composer
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    command: composer install
